data<-read.table("household_power_consumption.txt",sep=";",header=TRUE,na.strings="?",stringsAsFactors=FALSE)
data2<-subset(data,data$Date=="1/2/2007" | data$Date =="2/2/2007")
datetime <- strptime(paste(data2$Date,data2$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2),mar=c(4,4,2,2))
plot(datetime,data2$Global_active_power,type="l",ylab="Global Active Power",col="black",xlab="")
plot(datetime,data2$Voltage,type="l",ylab="Voltage",col="black")
plot(datetime,data2$Sub_metering_1,col="black",xlab="",ylab="Energy Sub Metering",type="l")
lines(datetime,data2$Sub_metering_2,col="red")
lines(datetime,data2$Sub_metering_3,col="blue")
legend("topright",lty=1,lwd=2.5,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_2"))
plot(datetime,data2$Global_reactive_power,type="l",col="black",xlab="Global_reative_power")
dev.off()