data<-read.table("household_power_consumption.txt",sep=";",header=TRUE,na.strings="?",stringsAsFactors=FALSE)
data2<-subset(data,data$Date=="1/2/2007" | data$Date =="2/2/2007")
png("plot1.png", width=480, height=480)
hist(data2$Global_active_power,col="red",xlab="Global Active Power",main="Global Active Power")
dev.off()